[versions]
activity-compose = "1.9.0-alpha03"
# Plugins
android-gradle-plugin = "8.3.0"
ben-manes-gradle = "0.51.0"
chucker = "4.0.0"
coil-compose = "2.6.0"
# Firebase
com-google-services = "4.4.1"
compose-bom = "2024.02.01"
compose-navigation = "2.8.0-alpha03"
# Android X
core-ktx-version = "1.13.0-alpha05"
coroutines-test = "1.8.0"
crashlytics-plugin = "2.9.9"
datastore = "1.1.0-beta01"
firebase-bom = "32.7.3"
compose-constraint ="1.0.1"

# DI
hilt = "2.51"
hilt-nav-compose = "1.2.0"
# Testing
junit = "4.13.2"
kotlin-android = "1.9.22"
kotlin-serialization = "1.9.22"
kotlinx-coroutines-android = "1.8.0"
kotlinx-serialization = "1.6.3"
kotlinx-serialization-converter = "1.0.0"
lifecycle-runtime-ktx = "2.8.0-alpha02"
lifecycle-viewmodel-compose = "2.8.0-alpha02"
# Versioning
mapsplatform-secrets = "2.0.1"
mockk = "1.13.3"
okhttp = "4.10.0"
# Play Services
play-services-location = "21.1.0"
# Async
retrofit = "2.9.0"
truth = "1.4.2"
turbine = "1.0.0"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
#chucker
chucker-debug = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-release = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
com-firebase-crashlytics-plugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics-plugin" }
#Firebase
com-google-services = { module = "com.google.gms:google-services", version.ref = "com-google-services" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-viewmodel-lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
compose-constraint = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "compose-constraint" }
#AndroidX
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx-version" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

#DI
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-nav-compose = {group="androidx.hilt", name="hilt-navigation-compose", version.ref="hilt-nav-compose"}

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization-converter" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
mock-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }
mock-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
playservices-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
# Async
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "mapsplatform-secrets" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization" }

[bundles]
androidx = [
    "activity-compose",
    "core-ktx",
    "datastore",
    "hilt-nav-compose",
    "lifecycle-runtime-ktx",
]
compose = [
    "compose-material",
    "compose-navigation",
    "compose-preview",
    "compose-ui",
    "compose-viewmodel-lifecycle",
    "compose-constraint",
]
firebase = [
    "firebase-analytics",
    "firebase-crashlytics",
]
