[versions]
# Plugins
android-gradle-plugin = "8.0.1"
kotlin-android = "1.8.20"
mapsplatform-secrets = "2.0.1"
hilt-plugin = "2.44"
kotlin-serialization = "1.6.10"
# Android X
core-ktx-version = "1.10.0"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.1"
compose = "1.4.2"
compose-navigation = "2.5.3"
datastore = "1.0.0"
lifecycle-viewmodel-compose = "2.6.1"
androidxWork = "2.8.1"
# Play Services
play-services-location = "21.0.1"
# DI
hilt = "2.44"
# Async
retrofit = "2.9.0"
coil-compose = "2.2.2"
kotlinx-serialization = "1.4.1"
kotlinx-serialization-converter = "0.8.0"
kotlinx-coroutines-android = "1.6.4"
okhttp = "4.10.0"
# Testing
junit = "4.13.2"
turbine = "0.12.1"
mockk = "1.13.3"
truth = "1.1.3"
coroutines-test = "1.6.4"
core-testing = "2.2.0"
robolectric = "4.9.2"
core-ktx = "1.5.0"
# Firebase
com-google-services = "4.3.15"
firebase-bom = "32.0.0"
crashlytics-plugin = "2.9.5"
# Room
room = "2.5.1"
hiltExt = "1.0.0"

#Gson
gson = "2.9.0"

#Timber
timber = "5.0.1"

[libraries]
#AndroidX
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx-version" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
#DI
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
compose-viewmodel-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
playservices-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location" }
# Async
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization-converter" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
#Timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
mock-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mock-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
androidx-arch-core= { group = "androidx.arch.core", name = "core-testing", version.ref = "core-testing" }
roboelectric= { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
androidx-work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
androidx-work-testing = { group = "androidx.work", name = "work-testing", version.ref = "androidxWork" }
core-ktx-test = { group = "androidx.test", name = "core-ktx", version.ref = "core-ktx" }

#Firebase
com-google-services = { group = "com.google.gms", name = "google-services", version.ref = "com-google-services" }
com-firebase-crashlytics-plugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "crashlytics-plugin" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }

#Room
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
#Gson
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "gson" }


[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "mapsplatform-secrets" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-plugin" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization" }

[bundles]

androidx = [
    "core-ktx",
    "lifecycle-runtime-ktx",
    "activity-compose",
    "compose-ui",
    "compose-preview",
    "compose-material",
    "compose-navigation",
    "datastore",
    "compose-viewmodel-lifecycle"
]

firebase = [
    "firebase-analytics",
    "firebase-crashlytics"
]
